name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run check
        run: cargo check
      - name: Run lint
        run: cargo fmt
      - name: Run build
        run: cargo build
      - name: Run test
        run: cargo test
